# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 CESNET.
#
# invenio-integration-tests is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

language: python
python:
  - "3.8"
  
notifications:
  email: # sent to the committer and the author
    on_success: never # default: always
    on_failure: never # default: always   #TODO: change to always

branches:
  only:
  - master

env:
  global:
    - E2E=no
  matrix:
    - REQUIREMENTS=test EXTRAS=invenio3.2

cache: pip

#addons:
#  postgresql: 9.6

#services:
#  - postgresql
#  - redis
#  - rabbitmq

before_install:
  # Stop default travis services
  - "sudo service mysql stop"
  - "./scripts/init ${EXTRAS}"

install:
  - "./scripts/bootstrap"

script:
  - ./run_tests.sh

before_deploy:
  - git config --local user.name "travis"
  - git config --local user.email "hlava@cesnet.cz"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: script
  script: git add upload/requirements.txt && git commit -m 'travis upload' && git push origin master
  skip_cleanup: true
  draft: true
  overwrite: true
