# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 CESNET.
#
# invenio-integration-tests is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

language: python
python:
  - "3.8"
  
notifications:
  email: # sent to the committer and the author
    on_success: never # default: always
    on_failure: never # default: always   #TODO: change to always

branches:
  only:
  - master

env:
  global:
    - E2E=no
  matrix:
    - REQUIREMENTS=test EXTRAS=invenio3.2

cache: pip

#addons:
#  postgresql: 9.6

#services:
#  - postgresql
#  - redis
#  - rabbitmq

before_install:
  # Stop default travis services
  - "sudo service mysql stop"
  - "./scripts/init ${EXTRAS}"

install:
  - "./scripts/bootstrap"

script:
  - ./run_tests.sh

deploy:
  provider: releases
  token: "pYDiAmOE/S2GZuFxMOHluIEMriuKu09Ip9/DVN89WfkBKvGcSpsdBXZZWrrAjOQvTB1NEu/6TXJJx4oPlQnAUJP3+IHuFe74lMoBN92k6Ecu2BbLH3RDiUL3LJGL/wD756sIu2jTN9H1D0eO9ANF+9sjHk6off7DMz9jYdMGtuUByRdI0gOBsznMNGR9TLA8GcE068OJvg1aATzOJ8yAtX9GtiFsO0Tib7HvOyHSN3W+Bh8daT0x1prHObGBEbCmIyhiMlnufpBSmy/M6AeoaRqARLGFoaS9Gri9ZNVdHAHsFY0vhEKbFTG6iU4ClE/dYVj97U6ch5IykcCRONRUiEVGlLbDKbyTo/C63X+RbA+D6MpWSE8HqPxPWfEW+NJjGrMIstBMk4MWD6LFall/IuVD9M1z/Ck+7L/towDpsplXiMI+5/Lpbtr8DlFYoLhWNekWP8mPFkfl5KM3b5nWpuC/QIUZItt4xeMgqmLzIjpgKfDbVNLFOM3TRGU62sQB/DKyWqbyTbJ697ISGfw/N91aAy7UMAqxFWxBojqnCsFPCsALT+59ESk8I1qEH11j6oaJJrY6ayfFenarvAWlMyXxMWVV9d9Rz1YEjYxJoZsla00SfaJzhOWaNw00EExs7v4uWEEzwcC35YBA3wpJ/tg9J14Q7QIu3dloY03Uo5U="
  file: ".requirements.txt"
  skip_cleanup: true
  draft: true
  overwrite: true
