# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 CESNET.
#
# invenio-integration-tests is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: cron wf wrapper

on:
  schedule:
    # every sat. at 7:39 GMT
    - cron: '39 7 * * 6'
    # debug run
    - cron: '10 12 * * *'
  workflow_dispatch:

jobs:
  cron-wf-trig:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        branch: [ 'master', 'invenio-3.5' ]
    steps:
      - name: Trig workflow in ${{ matrix.branch }} br.
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: 4008431
          token: ${{ secrets.OAR_BOT }}
          ref: ${{ matrix.branch }}
