name: Invenio requirements biulder (ported from travis)

on:
  push:
    branches: [ test ]

jobs:
  build:
#    runs-on: ubuntu-20.04
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        include:
          - extras: 'invenio3.3'
            requirements: 'invenio3.3'
          - extras: 'invenio3.3test'
            requirements: 'invenio3.3test'
          - extras: 'devel'
            requirements: 'devel'
          - extras: 'devel_test'
            requirements: 'devel_test'
    env:
      ES7_DOWNLOAD_URL: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.2.0-linux-x86_64.tar.gz"
      EXTRAS: ${{ matrix.extras }}
      REQUIREMENTS: ${{ matrix.requirements }}
      OAR_BOT: '${{ secrets.OAR_BOT }}'
    steps:
      - name: Checkout oarepo/invenio-integration-tests
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
#      - name: Display Python version
#        run: python -c "import sys; print(sys.version)"
      - name: init
        env:
          ES_URL: ${{ env.ES7_DOWNLOAD_URL }}
        run: |
          echo "EXTRAS:$EXTRAS; REQUIREMENTS:$REQUIREMENTS; ES_URL:$ES_URL;"
          ./scripts/init
      - name: install (bootstrap)
        run: |
          ./scripts/bootstrap
      - name: run_test
        run: |
          ./run_tests.sh
      - name: push results
        run: |
          ./scripts/test_push.sh
