# This is a basic workflow to help you get started with Actions

name: test1

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
#    branches: [ master ]
    branches: [ actions-tests ]
    paths: [ 'upload/*' ]
  #workflow_dispatch:
  #  inputs:
  #    txt:
  #      decription: TXT_field
  #      required: true
  #      default: Lorem ipsum

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo test1 output1

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script - echo + diff
      env:
        TOK: ${{ secrets.integration_test }}
      run: |
        echo test1 output2 line1
        git log -1 --stat upload
        git status
        git branch -avv
        echo ${{ github.event.before }}
        echo ${{ github.sha }}
        git diff --name-only ${{ github.sha }}
        echo ".${{ secrets.integration_test }}."
        echo ".$env:TOK."
        #git diff --name-only ${{ github.event.before }} ${{ github.sha }}
        echo "Done."
        
